tazama-lf/frms-coe-lib

- .eslintrc.js
- __tests__/dbManager.test.ts
- package-lock.json
- package.json
- src/services/dbManager.ts
- src/services/redis.ts
getIncomingPacs002Edges(accountId: string, limit?: number)
getOutgoingPacs002Edges(accountId: string, limit?: number)
Redis.quit now forcefully disconnects
Updated Linting to disable `optional chaining`
> Added new methods

- package-lock.json
- package.json
- src/services/dbManager.ts
`isReadyCheck()` returns a `Record<string, unknown>` derived from a list internally. This allows us to return it directly
> refactor: use Record type directly for isReadyCheck()

- package.json
- src/services/redis.ts
Scard is 0(1) complexity vs smembers being an 0(N) complexity. 
https://redis.io/commands/scard/
https://redis.io/commands/smembers/
> feat: Add Add One Get Count method to lib

- package-lock.json
- package.json
- src/interfaces/apm.ts
- src/services/apm.ts
This should help keep the interface to the underlying `elastic-apm` agent always compatible.
Related to https://github.com/frmscoe/General-Issues/issues/238
> refactor: use upstream ApmOptions

- package-lock.json
- package.json
- src/helpers/schemas/message.ts
`status` field is not included in the message to `tadproc`
> fix: make `status` optional

- package-lock.json
- package.json
- src/services/logger.ts
Related to https://github.com/frmscoe/General-Issues/issues/254
This PR initialises **all** `log` calls below the configured level to return `null`, bypassing the need to check every time what log level was configured and whether or not we can output the current log.
> feat: disable log levels below the configured level

- package-lock.json
- package.json
- src/builders/transactionHistoryBuilder.ts
- src/helpers/schemas/message.ts
- src/services/redis.ts
Related to https://github.com/frmscoe/General-Issues/issues/263
Refactoring: removed useless JSON serialization 
Used Protobuf bit to store data to Redis encoding and decoding
this PR support : https://github.com/frmscoe/typology-processor/pull/68 Typology processor and other processors that might be using the methods refactorized
This PR is a blocker to #68
> Protobuf redis

- package-lock.json
- package.json
- src/helpers/proto/Full.proto
- src/helpers/schemas/message.ts
Resolution of issue https://github.com/frmscoe/General-Issues/issues/287
Seems like the idea of having cfg for networkmap is not new since it is already present on the interface it was just missing from the definition of protobuf and json schema
> Networkmap version

- package-lock.json
- package.json
- src/helpers/calculatePrcg.ts
- src/services/redis.ts
Add calculated function to library
And
Undeprecated addOneGetAllMembers of Redis Service
Related To #https://github.com/frmscoe/General-Issues/issues/324
> fix: undeprecated addOneGetAll from redis service

- package-lock.json
- package.json
- src/interfaces/Pacs.002.001.12.ts
- src/interfaces/Pacs.008.001.10.ts
- src/interfaces/Pain.001.001.11.ts
- src/interfaces/Pain.013.001.09.ts
In Relation: https://github.com/frmscoe/frms-coe-lib/issues/132
We added the cache object to the Transaction Interfaces. 
So that when the transaction gets saved and retrieved from arango, the datacache is present for lookup purposes.
> feat: attaching cache to transactions

- __tests__/dbManager.test.ts
- package-lock.json
- package.json
- src/builders/pseudonymsBuilder.ts
- src/interfaces/ArangoCollections.ts
- src/interfaces/database/PseudonymsDB.ts
Removed specifying keys for edges. Also created two new methods for account related edges. Updated account conditions retrieval query to use the new edges.
https://github.com/frmscoe/admin-service/issues/64 and https://github.com/frmscoe/admin-service/issues/60
> fix: remove key override and edge separation

- __tests__/utils.test.ts
- package-lock.json
- package.json
- src/helpers/proto/EFRuP.proto
- src/helpers/protobuf.ts
- src/interfaces/event-flow/ConditionDetails.ts
Add helper functions to encode/decode EFRuP conditions to Buffers
All cache writes should store buffers
> feat: proto encode/decode EFRUP conditions 

- package-lock.json
- package.json
**This version contains Changes of**f: https://github.com/tazama-lf/frms-coe-lib/pull/167
We are bumping the version of the library
Because we have published the current version
> refactor: bump lib version

- package-lock.json
- package.json
- src/services/redis.ts
1. set method of caching data
1. To allow integrators to cache forever
PR related to issue: https://github.com/frmscoe/admin-service/issues/81
> fix: allow forever cache

- src/helpers/env/redis.config.ts
Reused the existing RedisConfig
No dupes
> refactor: reuse available redis config

- src/helpers/env/database.config.ts
- src/helpers/env/index.ts
- src/helpers/env/monitoring.config.ts
- src/helpers/env/redis.config.ts
Reused the existing DbConfig type and reexported helpers in the env module
Less imports downstream
> feat: optional variables

- README.md
- __tests__/dbManager.test.ts
- src/builders/configurationBuilder.ts
- src/helpers/env/database.config.ts
- src/helpers/env/index.ts
- src/helpers/env/localcache.config.ts
- src/helpers/env/redis.config.ts
- src/interfaces/RedisConfig.ts
- src/services/dbManager.ts
1. Separated cache options
To ensure these options cache used by resource targeted only
> fix: split cache options

- src/helpers/env/database.config.ts
- src/helpers/env/index.ts
Align auth state with variables
> fix: db user is not required if auth is disabled

- LICENSE
> fix: Issue 227 Add Tazama into to LICENSE

- __tests__/dbManager.test.ts
- package-lock.json
- package.json
- src/helpers/proto/Full.proto
- src/interfaces/Pacs.008.001.10.ts
- src/interfaces/Pain.001.001.11.ts
- src/interfaces/rule/DataCache.ts
We added the intrBkSttlmAmt property to the datacache and updated some out of date tests
So we can support multi-currency transactions. The tests were required for coverage.
> feat: Multi currency cache

- README.md
- VARIABLES.md
Added documentation to explain the behavior of the library after encapsulation of the environment variables
To allow ease of integration of the library
> docs: add documentation for encapsulation of environment variables

- __tests__/collections.test.ts
- __tests__/dbManager.test.ts
- package-lock.json
- package.json
- src/builders/transactionBuilder.ts
- src/builders/transactionHistoryBuilder.ts
- src/interfaces/ArangoCollections.ts
- src/interfaces/database/TransactionDB.ts
- src/interfaces/database/TransactionHistoryDB.ts
We updated the Arango schema 
We added save transaction history functions
To allow consistency across the platform
To use the Arango schema for every Arango call functions
> refactor: update arango schema

- package-lock.json
- package.json
- src/interfaces/Pacs.008.001.10.ts
- src/interfaces/Pain.013.001.09.ts
- src/tests/data/pacs008.ts
- src/tests/data/pain013.ts
Add missing message fields in Pain013 and Pacs008 interfaces
(linked issues)
> fix: missing fields in message types
