- __tests__/dbManager.test.ts
- package.json
- src/services/dbManager.ts
Added generic methods for each database
> Split up database builder logic

- __tests__/dbManager.test.ts
- package.json
- src/services/dbManager.ts
Also modify generic queries to contain "FILTER" internally, so we future proof ourselves.
> Add networkmap

- package-lock.json
- package.json
- src/services/dbManager.ts
> Jsdoc Additions

- .eslintignore
- __tests__/collections.test.ts
- __tests__/dbManager.test.ts
- package-lock.json
- package.json
- setup.jest.js
- src/interfaces/ArangoCollections.ts
- src/services/dbManager.ts
- src/services/redis.ts
Exposed private redis client
Updated tests
Added setup.jest.js to eslintignore
> Added isReadyCheck

- __tests__/dbManager.test.ts
- package-lock.json
- package.json
- src/services/dbManager.ts
- src/services/redis.ts
Renamed Previous getJSON to getMembers, and implemented proper get functionality.
> Added Redis GetJSON function 

- __tests__/dbManager.test.ts
- package-lock.json
- package.json
- src/services/dbManager.ts
Added a Get Transaction Pain001 Function to the Transaction History Database Manager.
> Get transaction pain001 Function

- package-lock.json
Updated package-lock.json so CI can actually get latest changes for Log4js that was installed.
> BUG: Update package-lock.json

- package-lock.json
- package.json
- src/helpers/unwrap.ts
> FIX: default to undefined if indexing errors occur

- package-lock.json
- package.json
- src/interfaces/processor-files/Alert.ts
- src/interfaces/processor-files/CMSRequest.ts
- src/interfaces/processor-files/ChannelResult.ts
- src/interfaces/processor-files/TADPResult.ts
- src/interfaces/processor-files/TransactionConfiguration.ts
- src/interfaces/processor-files/TypologyResult.ts
- src/interfaces/rule/RuleRequest.ts
Added CADP and TADP classes to the library.
> FEAT: Add More Classes

- package-lock.json
- package.json
- src/interfaces/rule/RuleResult.ts
Related to https://github.com/frmscoe/General-Issues/issues/153
> Add perfomance attribute

- package-lock.json
- package.json
- src/builders/pseudonymsBuilder.ts
Related to https://github.com/frmscoe/General-Issues/issues/236
🐛 fix
> Account holder data dupe

- package-lock.json
- package.json
- src/interfaces/apm.ts
- src/services/apm.ts
Related to: https://github.com/frmscoe/General-Issues/issues/238
> feat: add apm service

- __tests__/dbManager.test.ts
- package-lock.json
- package.json
- src/builders/configurationBuilder.ts
- src/interfaces/database/ConfigurationDB.ts
In Relation to: https://github.com/frmscoe/General-Issues/issues/245. Required for Merge : https://github.com/frmscoe/transaction-aggregation-decisioning-processor/pull/46
> Cache config

- package-lock.json
- package.json
- src/helpers/schemas/message.ts
- src/interfaces/rule/RuleResult.ts
Related to https://github.com/frmscoe/General-Issues/issues/232
Merge after https://github.com/frmscoe/frms-coe-lib/pull/58
> feat: adding weight for rule result

- package-lock.json
- package.json
- src/builders/redisBuilder.ts
- src/helpers/protobuf.ts
- src/services/redis.ts
Related to https://github.com/frmscoe/General-Issues/issues/262
Protobuf as supplementary to writing bytes to redis.
Also eases the restrictions of types that can be written to Redis
> feat: write bytes to redis

- package-lock.json
- package.json
- src/helpers/schemas/message.ts
- src/services/redis.ts
> Protobuf redis

- package-lock.json
- package.json
- src/helpers/proto/Full.proto
> fix: use timestamp type for timestamp field

- package-lock.json
- package.json
- src/services/redis.ts
Related: https://github.com/frmscoe/General-Issues/issues/271
> Redis connection lost handling

- package-lock.json
- package.json
- src/builders/transactionHistoryBuilder.ts
- src/interfaces/Pacs.002.001.12.ts
- src/interfaces/Pacs.008.001.10.ts
- src/interfaces/Pain.001.001.11.ts
- src/interfaces/Pain.013.001.09.ts
Related to https://github.com/frmscoe/General-Issues/issues/144
> Rooted attributes

- package-lock.json
- package.json
- src/interfaces/processor-files/TypologyResult.ts
- src/interfaces/rule/RuleResult.ts
Related to: https://github.com/frmscoe/General-Issues/issues/281
> Remove description property for Rule and Typology Results

- package-lock.json
- package.json
- src/interfaces/processor-files/TypologyResult.ts
- src/services/redis.ts
In Relation to:  https://github.com/frmscoe/General-Issues/issues/15
> Add workflow

- package-lock.json
- package.json
- src/helpers/proto/Full.proto
- src/services/redis.ts
Bug Fix: Set Add to use protobuf encoder
Related to https://github.com/frmscoe/General-Issues/issues/324
> Set add redis

- package-lock.json
- package.json
- src/helpers/proto/Full.proto
- src/interfaces/processor-files/ChannelResult.ts
- src/services/redis.ts
Related to https://github.com/frmscoe/General-Issues/issues/323
> Remove status channel

- src/tests/data/index.ts
- src/tests/data/networkMap.ts
- src/tests/data/pacs002.ts
- src/tests/data/pacs008.ts
- src/tests/data/pain001.ts
- src/tests/data/pain013.ts
- src/tests/mocks/mock-networkmap.ts
- src/tests/mocks/mock-transactions.ts
Related to https://github.com/frmscoe/General-Issues/issues/123
> test: impl base fixtures

- package-lock.json
- package.json
- src/tests/data/dataCache.ts
- src/tests/data/index.ts
> Base fixtures

- package-lock.json
- package.json
- src/tests/data/expressions.ts
- src/tests/mocks/mock-transactions.ts
Adding Base fixures and fixing the mocks implementation
> fix: only mock if config provides values

- package-lock.json
- package.json
- src/helpers/networkMapIdentifiers.ts
Related to https://github.com/frmscoe/General-Issues/issues/310
> fix: helper for nats networkmap routing

- package-lock.json
- package.json
- src/builders/transactionHistoryBuilder.ts
Related to https://github.com/frmscoe/General-Issues/issues/364
> fix: typo in db field name

- package-lock.json
- package.json
- src/helpers/proto/Full.proto
Related to: https://github.com/frmscoe/General-Issues/issues/390
> revert: reserve fields

- __tests__/dbManager.test.ts
- package-lock.json
- package.json
- src/builders/transactionBuilder.ts
- src/interfaces/database/TransactionDB.ts
Blocker for https://github.com/frmscoe/admin-service/pull/6
> feat: add method for getting report by msgid

- .github/workflows/milestone.yml
- .github/workflows/release.yml
> feat: Added release and milestone workflows.

- package-lock.json
- package.json
Version bump
To coincide with the new library published
> build: version bump

- package-lock.json
- package.json
> build: bumped version for release 2.0.0

- README.md
1. Read me documentation 
1. To catch up on the documentation with the current library's functionality
> docs: full rework of readMe

- CHANGELOG.md
- VERSION
> Docs Merge

- package-lock.json
- package.json
- src/builders/pseudonymsBuilder.ts
- src/interfaces/event-flow/Condition.ts
We add condId on the type of condition
To be able to identify each condition without use of database native tools
These changes were requested by: https://github.com/frmscoe/admin-service/issues/65
> feat: Cond id auto gen using UUID v4

- package-lock.json
- package.json
- src/helpers/proto/Full.proto
Add EFRuP property to proto file
Parsing/Serializing of EFRuP property 
Related: tazama-lf/transaction-aggregation-decisioning-processor#199
> feat(proto): add flowprocessor to workflow

- __tests__/dbManager.test.ts
- setup.jest.js
- src/builders/pseudonymsBuilder.ts
- src/interfaces/database/PseudonymsDB.ts
We added test cases for testing our new functions
We added new update functions expiration time date for edges and conditions
We added Functions on the interface layer and documented 
To allow users to expire conditions.
To ensure that logic is tested
To allow ease of use for other developers
> feat: Update expire date

- __tests__/dbManager.test.ts
- __tests__/utils.test.ts
- src/builders/pseudonymsBuilder.ts
- src/helpers/proto/EFRuP.proto
- src/helpers/protobuf.ts
- src/interfaces/database/PseudonymsDB.ts
- src/interfaces/event-flow/EntityConditionEdge.ts
Added functions to get conditions, directly or through graphs
They need to be cached: https://github.com/tazama-lf/event-flow/issues/8
> feat: get conditions

- package-lock.json
- package.json
Prepare for v4.2.0-rc.0 release
Publishing lib artifact
> build: 4.2.0-rc.0

- package-lock.json
- package.json
Updated pkg metadata for next release
Preparing for release
> build: 4.2.0-rc.1

- package-lock.json
- package.json
> build: prepare 4.2.0-rc.2 release

- src/helpers/env/index.ts
default values for optional variables
> fix: optional variables

- package-lock.json
- package.json
> build: 4.2.0-rc.3

- package-lock.json
- package.json
Library version bump
Avoid packages conflict
> refactor: 5.0.0-rc.0

- package-lock.json
- package.json
script for building
bump version
ensure cleaning before building
no coflicts
> refactor: clean before build

- README.md
- __tests__/dbManager.test.ts
- package-lock.json
- package.json
- src/builders/pseudonymsBuilder.ts
- src/interfaces/database/PseudonymsDB.ts
Why changed 2 pseudonyms Builder functions to have optional parameter
We changed readMe.md
We bumped the library version
We added the optional parameter into the interface of pseudonyms Builder
We changed unit test adding new cases
We refined predicate of a active condition
To allow retrieving of all conditions and only active ones
To refine documentation
To resolve version conflict
To reference the new parameters
To test the case where the new optional argument is passed
To Ensure that currently active conditions are only conditions returned when requested
> fix: Retrieve condition - add option to return active and expired conditions

- package-lock.json
- package.json
- src/builders/pseudonymsBuilder.ts
We fixed arango aql from the Get function of Pseudonym Builder methods
To fix bug of returning condition we Submitting a condition
> fix: allow toVertex with null xprtnDtTm

- package-lock.json
- package.json
Updates to package.json to prepare for package publish and upcoming release
> build: version control for package publishing

- package-lock.json
- package.json
- src/interfaces/processor-files/TypologyConfig.ts
- src/interfaces/processor-files/TypologyResult.ts
Updated the typology interfaces.
Missed them in the previous iteration. Identified required changes later on.
> feat: updated missed interfaces

- package-lock.json
- package.json
package version update
Needed for publish
> build: version update to 6.0.0-rc.5

- package-lock.json
- package.json
- src/builders/pseudonymsBuilder.ts
Updated composite key
For multi-tenancy
> feat: updated account and entity
